#!/usr/bin/ruby
# -*- coding: utf-8 -*-

def systemAndDieIfFail cmd
    status = system cmd
    # raise cmd if status != 0
end

module NVIDIA
    def self.unload
        STDOUT.print "unloading..."
        systemAndDieIfFail "sudo rmmod nvidia_modeset"
        systemAndDieIfFail "sudo rmmod nvidia_uvm"
        systemAndDieIfFail "sudo rmmod nvidia"
        STDOUT.print "done\n"
    end

    def self.load
        STDOUT.print "loading..."
        systemAndDieIfFail "sudo modprobe nvidia"
        systemAndDieIfFail "sudo modprobe nvidia_modeset"
        systemAndDieIfFail "sudo modprobe nvidia_uvm"

        systemAndDieIfFail "sudo nvidia-smi -pm 1"
        # systemAndDieIfFail "sudo nvidia-smi -ac 3004,875"
        STDOUT.print "done\n"
    end
end

def main()
    NVIDIA::unload()
    NVIDIA::load()
end

main() if __FILE__ == $0
