#!/usr/bin/ruby
# -*- coding: utf-8 -*-
#  Copyright (C) 2016 Yusuke Suzuki <yusuke.suzuki@sslab.ics.keio.ac.jp>
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
#  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
#  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
#  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

require 'open3'
require 'fileutils'
require_relative './gloop.rb'
require_relative './benchmark-data.rb'

class Result
    def initialize(name)
        @name = name
    end
end

class BenchmarkResult < Result
    def initialize(name, data)
        super(name)
        @time = extractTime(data)
    end

    def report
        puts "#{@name}: #{@time.to_s}"
    end

    private
    def extractTime(data)
        m = /result:us\((\d+)\)/m.match(data)
        raise self unless m
        m[1].to_i
    end
end

class StatisticsResult < Result
    def initialize(name, data)
        super(name)
        @name = name
        @times = {
            "GPUInit" => 0,
            "DataInit" => 0,
            "IO" => 0,
            "Copy" => 0,
            "Kernel" => 0,
        }

        @times.each {|key, _|
            @times[key] = extractTime(key, data)
        }
    end

    def report
        result = 0
        @times.each {|key, value|
            result += value
        }
        puts "#{@name}: #{result.to_s}"
    end

    private
    def extractTime(type, data)
        m = /#{type} result:us\((\d+)\)/m.match(data)
        raise self unless m
        m[1].to_i
    end
end

class Test
    def initialize(name, times)
        @name = name
        @times = times
        @scheduler = nil
    end

    def execute
        setup
        results = runBenchmark()
        teardown
        results.each {|result|
            result.report()
        }
    end

    def setup
        @scheduler = Process.spawn(%W(#{GLoop::Root}/release/src/gloop/gloop-monitor 1).join(" "), :in => "/dev/null", :out => "/dev/null", :err => "/dev/null")
        sleep 1
        Process.detach @scheduler
    end

    def teardown
        Process.kill :INT, @scheduler
    end
end

class Throttles
    def initialize num, count
        @num = num
        if num == 1
            count = count
        elsif num == 3
            count = (count * 0.8).to_i
        elsif num == 7
            count = (count * 0.5).to_i
        end
        @count = count
        @processes = []
    end

    def command
        %W(#{GLoop::Root}/release/src/samples/throttle/throttle #{@count} 1 1 1 1)
    end

    def run
        @num.times {
            pid = Process.spawn(command().join(" "), :in => "/dev/null", :out => "/dev/null", :err => "/dev/null")
            # Process.detach pid
            @processes << pid
        }
        sleep 5
    end

    def kill
        @processes.each {|pid|
            # Process.kill :INT, pid
            Process.wait pid
        }
    end
end

class PriorityThrottles < Throttles
    def initialize num, count
        super(num, count)
        @priority = num * 2 # 66%
    end

    def command
        %W(#{GLoop::Root}/release/src/samples/proportional-throttle/proportional-throttle #{@count} 1 1 1 #{@priority})
    end
end

class SchedulingTest < Test
end

class GrepTextTest < SchedulingTest
    def createCommand
        %W(#{GLoop::Root}/release/src/samples/grep_text/grep_text_gloop 1 224 224 128 input/dict.gpu out db_shakespere.txt)
    end

    def runBenchmark
        throttles = Throttles.new(@times, 16000000)
        throttles.run
        result = nil
        FileUtils.chdir("#{GLoop::Root}/data") {|dir|
            threads = []
            out, err, status = Open3.capture3(createCommand().join(" "))
            FileUtils.rm "out" if File.exists? "out"
            result = BenchmarkResult.new(@name, err)
        }
        throttles.kill
        [ result ]
    end
end

class TPACFTest < SchedulingTest
    def createCommand
        [ "#{GLoop::Root}/release/src/samples/parboil2/tpacf-gloop/tpacf-gloop", "-i", BenchmarkData::TPACF::Data, "-o", "out", "--", "-n", "100", "-p", "10391" ]
    end

    def runBenchmark
        throttles = Throttles.new(@times, 20000000)
        throttles.run
        result = nil
        FileUtils.chdir("#{GLoop::Root}/data") {|dir|
            threads = []
            out, err, status = Open3.capture3(createCommand().join(" "))
            FileUtils.rm "out" if File.exists? "out"
            result = StatisticsResult.new(@name, err)
        }
        throttles.kill
        [ result ]
    end
end

class PriorityGrepTextTest < GrepTextTest
    def runBenchmark
        throttles = PriorityThrottles.new(@times, 16000000)
        throttles.run
        result = nil
        FileUtils.chdir("#{GLoop::Root}/data") {|dir|
            threads = []
            out, err, status = Open3.capture3(createCommand().join(" "))
            FileUtils.rm "out" if File.exists? "out"
            result = BenchmarkResult.new(@name, err)
        }
        throttles.kill
        [ result ]
    end
end

class PriorityTPACFTest < TPACFTest
    def runBenchmark
        throttles = PriorityThrottles.new(@times, 20000000)
        throttles.run
        result = nil
        FileUtils.chdir("#{GLoop::Root}/data") {|dir|
            threads = []
            out, err, status = Open3.capture3(createCommand().join(" "))
            FileUtils.rm "out" if File.exists? "out"
            result = StatisticsResult.new(@name, err)
        }
        throttles.kill
        [ result ]
    end
end

$tests = [
    TPACFTest.new("tpacf1", 1),
    # TPACFTest.new("tpacf3", 3),
    # TPACFTest.new("tpacf7", 7),
    PriorityTPACFTest.new("priority-tpacf1", 1),
    # PriorityTPACFTest.new("priority-tpacf3", 3),
    # PriorityTPACFTest.new("priority-tpacf7", 7),
    # GrepTextTest.new("grep_text1", 1),
    # GrepTextTest.new("grep_text3", 3),
    # GrepTextTest.new("grep_text7", 7),
    # PriorityGrepTextTest.new("priority-grep_text1", 1),
    # PriorityGrepTextTest.new("priority-grep_text3", 3),
    # PriorityGrepTextTest.new("priority-grep_text7", 7),
]

def main
    11.times do
        $tests.each {|test|
            test.execute
        }
    end
end

main() if __FILE__ == $0
