#!/usr/bin/ruby
# -*- coding: utf-8 -*-
#  Copyright (C) 2016 Yusuke Suzuki <yusuke.suzuki@sslab.ics.keio.ac.jp>
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
#  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
#  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
#  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

require 'open3'
require 'fileutils'
require_relative './gloop.rb'

class Result
    def initialize(name, data)
        @name = name
        @time = extractTime(data)
    end

    def report
        puts "#{@name}: #{@time.to_s}"
    end

    private
    def extractTime(data)
        m = /result:us\((\d+)\)/m.match(data)
        raise self unless m
        m[1].to_i
    end
end

class Test
    def initialize(name, args)
        @name = name
        @args = args
    end

    def execute
        args = @args.collect {|arg| arg.gsub("\n", "") }
        result = runBenchmark(args)
        result.report()
    end

    def cwd
        "#{GLoop::Root}/data"
    end

    def runBenchmark args
        err = nil
        out = nil
        FileUtils.chdir(cwd()) {|dir|
            out, err, status = Open3.capture3(args.join(" "))
            FileUtils.rm "out" if File.exists? "out"
        }
        Result.new(@name, err)
    end
end

class ImagingTest < Test
    def cwd
        "#{GLoop::Root}../gpufs/samples/img"
    end
end

$tests = [
    Test.new("gloop", %W(#{GLoop::Root}/release/src/samples/grep_text/grep_text_gloop 1 60 60 128 input/dict.gpu out db_shakespere.txt)),
    Test.new("gpufs", %W(#{GLoop::Root}/../gpufs/samples/grep_text/fs 1 60 128 input/dict.gpu out db_shakespere.txt)),
    Test.new("cuda", %W(#{GLoop::Root}/../gpufs/samples/grep_text/grep_text_gpu_nofs input/dict.gpu out db_shakespere.txt)),
    ImagingTest.new("gloop", %W(#{GLoop::Root}/release/src/samples/img_non_mmap/img_gloop_non_mmap 0 30 512 res_in out res_o_0 res_o_1 res_o_2)),
    ImagingTest.new("gpufs", %W(#{GLoop::Root}/../gpufs/samples/img/fs 0 30 512 res_in out res_o_0 res_o_1 res_o_2)),
]

def main
    $tests.each {|test|
        test.execute
    }
end

main() if __FILE__ == $0
